import { Profile, ProfileLink } from "./types";

const SEED_PROFILES: Profile[] = [
  {
    id: "demo-001",
    createdAt: "2026-03-10T09:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/kimjiwoo.png",
    name: "김지우",
    birthYear: "1997년",
    birthYearRange: "2006년 ~ 1997년",
    gender: "여자",
    region: "서울 서부",
    education: "서울 4년제 졸업",
    height: "161 ~ 165",
    job: "IT회사_디자이너",
    jobType: "대기업",
    salary: "4,000만원 이상 ~ 6,000만원 미만",
    smoking: "비흡연",
    mbti: "ENFP",
    charm: "밝은 에너지와 공감 능력이 좋아요",
    datingStyle: "매일 연락하고 주말마다 데이트하는 스타일",
    phone: "01012345678",
    idealHeight: "176 ~ 180",
    idealAge: "1996년 ~ 1994년",
    idealRegion: "서울 서부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "대기업",
    idealSalary: "6,000만원 이상 ~ 8,000만원 미만",
    priority: "키",
  },
  {
    id: "demo-002",
    createdAt: "2026-03-11T14:30:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "박현우",
    birthYear: "1995년",
    birthYearRange: "1996년 ~ 1994년",
    gender: "남자",
    region: "서울 동부",
    education: "SKY카포 졸업",
    height: "176 ~ 180",
    job: "금융회사_애널리스트",
    jobType: "대기업",
    salary: "6,000만원 이상 ~ 8,000만원 미만",
    smoking: "비흡연",
    mbti: "INTJ",
    charm: "차분하고 계획적인 성격, 요리를 잘해요",
    datingStyle: "서로의 시간을 존중하면서 깊게 만나는 스타일",
    phone: "01098765432",
    idealHeight: "161 ~ 165",
    idealAge: "2006년 ~ 1997년",
    idealRegion: "서울 동부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "대기업",
    idealSalary: "4,000만원 이상 ~ 6,000만원 미만",
    priority: "연봉",
  },
  {
    id: "demo-003",
    createdAt: "2026-03-12T08:15:00.000Z",
    blocked: false,
    imageUrl: "/uploads/leesaeyun.png",
    name: "이서연",
    birthYear: "1998년",
    birthYearRange: "2006년 ~ 1997년",
    gender: "여자",
    region: "경기 서부",
    education: "석사 졸업",
    height: "156 ~ 160",
    job: "연구소_연구원",
    jobType: "공기업",
    salary: "4,000만원 이상 ~ 6,000만원 미만",
    smoking: "비흡연",
    mbti: "ISFJ",
    charm: "따뜻하고 배려심이 깊어요, 편지 쓰는 걸 좋아해요",
    datingStyle: "소소한 일상을 함께 나누는 스타일",
    phone: "01055556666",
    idealHeight: "171 ~ 175",
    idealAge: "1996년 ~ 1994년",
    idealRegion: "경기 서부",
    idealSmoking: "비흡연",
    idealEducation: "석사 졸업",
    idealJobType: "중견기업",
    idealSalary: "4,000만원 이상 ~ 6,000만원 미만",
    priority: "학력",
  },
  {
    id: "demo-m01",
    createdAt: "2026-03-08T10:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "최준혁",
    birthYear: "1993년",
    birthYearRange: "1993년 ~ 1990년",
    gender: "남자",
    region: "서울 남부",
    education: "SKY카포 졸업",
    height: "181 ~ 185",
    job: "법률사무소_변호사",
    jobType: "전문직",
    salary: "1억원 이상 ~ 1억 5천 미만",
    smoking: "비흡연",
    mbti: "ENTJ",
    charm: "목표 지향적이고 리더십이 강해요",
    datingStyle: "함께 성장하는 관계를 추구해요",
    phone: "01011112222",
    idealHeight: "161 ~ 165",
    idealAge: "1996년 ~ 1994년",
    idealRegion: "서울 남부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "대기업",
    idealSalary: "4,000만원 이상 ~ 6,000만원 미만",
    priority: "학력",
  },
  {
    id: "demo-m02",
    createdAt: "2026-03-08T11:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "김도윤",
    birthYear: "1996년",
    birthYearRange: "1996년 ~ 1994년",
    gender: "남자",
    region: "서울 서부",
    education: "서울 4년제 졸업",
    height: "176 ~ 180",
    job: "IT회사_백엔드개발자",
    jobType: "대기업",
    salary: "6,000만원 이상 ~ 8,000만원 미만",
    smoking: "비흡연",
    mbti: "INTP",
    charm: "유머 감각이 좋고 새로운 기술에 관심이 많아요",
    datingStyle: "편하게 대화 나누며 같이 취미 생활하는 스타일",
    phone: "01022223333",
    idealHeight: "156 ~ 160",
    idealAge: "2006년 ~ 1997년",
    idealRegion: "서울 서부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "대기업",
    idealSalary: "4,000만원 이상 ~ 6,000만원 미만",
    priority: "거주지",
  },
  {
    id: "demo-m03",
    createdAt: "2026-03-09T09:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "정민수",
    birthYear: "1994년",
    birthYearRange: "1996년 ~ 1994년",
    gender: "남자",
    region: "경기 동부",
    education: "석사 졸업",
    height: "171 ~ 175",
    job: "제약회사_연구원",
    jobType: "중견기업",
    salary: "4,000만원 이상 ~ 6,000만원 미만",
    smoking: "비흡연",
    mbti: "ISFP",
    charm: "감성적이고 음악을 좋아해요, 기타 연주 가능",
    datingStyle: "카페에서 조용히 시간 보내는 걸 좋아해요",
    phone: "01033334444",
    idealHeight: "156 ~ 160",
    idealAge: "1996년 ~ 1994년",
    idealRegion: "경기 동부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "중견기업",
    idealSalary: "3,000만원 이상 ~ 4,000만원 미만",
    priority: "흡연 여부",
  },
  {
    id: "demo-m04",
    createdAt: "2026-03-09T10:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "이승우",
    birthYear: "1992년",
    birthYearRange: "1993년 ~ 1990년",
    gender: "남자",
    region: "서울 북부",
    education: "의대,치대,한의대,약대 졸업",
    height: "176 ~ 180",
    job: "대학병원_내과전공의",
    jobType: "전문직",
    salary: "8,000만원 이상 ~ 1억원 미만",
    smoking: "비흡연",
    mbti: "ESTJ",
    charm: "책임감이 강하고 성실해요",
    datingStyle: "바쁘지만 시간 내서 꼭 챙기는 스타일",
    phone: "01044445555",
    idealHeight: "161 ~ 165",
    idealAge: "1996년 ~ 1994년",
    idealRegion: "서울 북부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "전문직",
    idealSalary: "4,000만원 이상 ~ 6,000만원 미만",
    priority: "연봉",
  },
  {
    id: "demo-m05",
    createdAt: "2026-03-09T14:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "한지훈",
    birthYear: "1997년",
    birthYearRange: "2006년 ~ 1997년",
    gender: "남자",
    region: "인천",
    education: "해외대학교 졸업",
    height: "181 ~ 185",
    job: "무역회사_해외영업",
    jobType: "중견기업",
    salary: "4,000만원 이상 ~ 6,000만원 미만",
    smoking: "흡연(전자담배)",
    mbti: "ENFJ",
    charm: "사교적이고 영어 가능, 여행을 좋아해요",
    datingStyle: "함께 여행 다니며 추억 쌓는 스타일",
    phone: "01055557777",
    idealHeight: "156 ~ 160",
    idealAge: "2006년 ~ 1997년",
    idealRegion: "인천",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "대기업",
    idealSalary: "3,000만원 이상 ~ 4,000만원 미만",
    priority: "나이",
  },
  {
    id: "demo-m06",
    createdAt: "2026-03-10T08:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "오태현",
    birthYear: "1990년",
    birthYearRange: "1993년 ~ 1990년",
    gender: "남자",
    region: "서울 동부",
    education: "서울 4년제 졸업",
    height: "185 이상",
    job: "스타트업_대표",
    jobType: "개인사업/자영업",
    salary: "2억 이상 ~",
    smoking: "비흡연",
    mbti: "ENTP",
    charm: "도전적이고 아이디어가 넘쳐요",
    datingStyle: "자유롭지만 진지할 땐 확실한 스타일",
    phone: "01066668888",
    idealHeight: "166 ~ 170",
    idealAge: "1996년 ~ 1994년",
    idealRegion: "서울 동부",
    idealSmoking: "비흡연",
    idealEducation: "SKY카포 졸업",
    idealJobType: "대기업",
    idealSalary: "4,000만원 이상 ~ 6,000만원 미만",
    priority: "직업 형태",
  },
  {
    id: "demo-m07",
    createdAt: "2026-03-10T15:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "윤성진",
    birthYear: "1991년",
    birthYearRange: "1993년 ~ 1990년",
    gender: "남자",
    region: "경기 서부",
    education: "기타 4년제 졸업",
    height: "171 ~ 175",
    job: "공무원_소방관",
    jobType: "공무원",
    salary: "4,000만원 이상 ~ 6,000만원 미만",
    smoking: "비흡연",
    mbti: "ISTP",
    charm: "듬직하고 운동을 좋아해요, 체력이 좋아요",
    datingStyle: "말보다 행동으로 보여주는 스타일",
    phone: "01077779999",
    idealHeight: "156 ~ 160",
    idealAge: "1993년 ~ 1990년",
    idealRegion: "경기 서부",
    idealSmoking: "비흡연",
    idealEducation: "기타 4년제 졸업",
    idealJobType: "공무원",
    idealSalary: "3,000만원 이상 ~ 4,000만원 미만",
    priority: "거주지",
  },
  {
    id: "demo-m08",
    createdAt: "2026-03-11T09:00:00.000Z",
    blocked: false,
    imageUrl: "/uploads/packhyunwoo.png",
    name: "강민재",
    birthYear: "1998년",
    birthYearRange: "2006년 ~ 1997년",
    gender: "남자",
    region: "서울 남부",
    education: "서울 4년제 졸업",
    height: "176 ~ 180",
    job: "광고회사_AE",
    jobType: "중견기업",
    salary: "3,000만원 이상 ~ 4,000만원 미만",
    smoking: "비흡연",
    mbti: "ESFP",
    charm: "밝고 활발해서 분위기 메이커예요",
    datingStyle: "매일 보고 싶고 스킨십 좋아하는 스타일",
    phone: "01088880000",
    idealHeight: "156 ~ 160",
    idealAge: "2006년 ~ 1997년",
    idealRegion: "서울 남부",
    idealSmoking: "비흡연",
    idealEducation: "서울 4년제 졸업",
    idealJobType: "대기업",
    idealSalary: "3,000만원 이상 ~ 4,000만원 미만",
    priority: "키",
  },
];

let profiles: Profile[] = [...SEED_PROFILES];
let links: ProfileLink[] = [];

export function getProfiles(): Profile[] {
  return profiles;
}

export function getProfile(id: string): Profile | undefined {
  return profiles.find((p) => p.id === id);
}

export function addProfile(profile: Profile) {
  profiles.push(profile);
}

export function updateProfile(id: string, updates: Partial<Profile>): Profile | undefined {
  const profile = profiles.find((p) => p.id === id);
  if (profile) {
    Object.assign(profile, updates);
  }
  return profile;
}

export function toggleBlock(id: string): Profile | undefined {
  const profile = profiles.find((p) => p.id === id);
  if (profile) {
    profile.blocked = !profile.blocked;
  }
  return profile;
}

export function getLinks(): ProfileLink[] {
  return links;
}

export function addLink(link: ProfileLink) {
  links.push(link);
}

export function getLinkByToken(token: string): ProfileLink | undefined {
  return links.find((l) => l.token === token);
}
